server:
  port: 8000

services:
  url:
    core: http://localhost:8080
    core-frontend: http://localhost:5173
    admintool-core:
    admintool-frontend:
spring:
  cloud:
    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 655460
